### PR TITLE
Clojure Russia added

### PR DESCRIPTION
**Pull request by zavg**

### CODE REVIEW

**Comment by mr-mig** [comment]
:+1:

**Comment by mr-mig** [comment]
I have the only question - is there a permanent link to the Hangouts?
I can see only the link for a meetup group.

**Comment by zavg** [comment]
Since all hangouts are recorded to YouTube, there is a separate Hangout on Air for each meeting.
The meetup group you can see is dedicated to manage and hold these Google Hangouts meetings.

**Comment by mr-mig** [comment]
Hm, I am doubting a bit to merge it, as the list is a collection of chat rooms, where people can interact with each other.
Maybe it's a better idea to create a separate repo for Hangouts? WDYT?

**Comment by zavg** [comment]
They also have Slack chat. So I have corrected the information in 2 last commits. 
The links to Google Hangouts meetings that I mentioned before are always available in this Slack chat.

**Comment by mr-mig** [comment]
Ok, great! 
Thanks for clearing that out!

**Pull request merged**
